spring.application.name=spring-glowroot-benchmark
spring.main.banner-mode=off
spring.jmx.enabled=false
logging.level.root=ERROR
server.port=8080
server.tomcat.threads.max=32
server.tomcat.threads.min-spare=1
server.tomcat.accept-count=256
server.tomcat.max-connections=512
server.tomcat.max-keep-alive-requests=10000
server.jetty.threads.max=32
server.jetty.threads.min=1
server.jetty.threads.max-queue-capacity=256
server.jetty.acceptors=1
server.jetty.selectors=1
server.jetty.max-connections=512
server.undertow.threads.io=1
server.undertow.threads.worker=32
server.undertow.buffer-size=16384
server.undertow.direct-buffers=true
