spring.application.name=spring-glowroot-benchmark
spring.main.banner-mode=off
spring.jmx.enabled=false
logging.level.root=ERROR
server.port=8080
server.tomcat.threads.max=32
server.tomcat.threads.min-spare=1
server.tomcat.accept-count=256
server.tomcat.max-connections=512
server.tomcat.max-keep-alive-requests=10000
